# Generated by Django 3.2.8 on 2022-09-08 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('proposed_finish_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('ongoing', 'ONGOING'), ('finished', 'COMPLETED')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('proposed_finish_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('ongoing', 'ONGOING'), ('finished', 'COMPLETED')], max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='page.project')),
            ],
        ),
    ]
